# Generated by Django 2.2.5 on 2019-09-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prep_time', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'beginner'), ('normal', 'normal'), ('master', 'master')], max_length=100)),
            ],
        ),
    ]
